#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          ashasiscontroller
# Required-Start:    $remote_fs $syslog mysql networking udev openhab
# Required-Stop:     $remote_fs $syslog mysql networking udev openhab
# Should-Start:      $network $time
# Should-Stop:       $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start and stop the ashasis controller
# Description:       
### END INIT INFO
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DESC="ashasis controller"
NAME=ashasiscontroller
DAEMON=/usr/bin/npm
DAEMONARGS=start
PIDFILE=/var/run/${NAME}.pid
SCRIPTNAME=$0
FOLDER=/opt/controller/
LOGFILE=/var/log/ashasis/controller.log
LOGDIR=$(dirname $LOGFILE)
if [ ! -d $LOGDIR ]; then
	mkdir -p $LOGDIR
fi

. /lib/init/vars.sh

case $1 in
	start)
		/sbin/start-stop-daemon --start --make-pidfile --chdir $FOLDER --pidfile $PIDFILE --exec $DAEMON -- $DAEMONARGS >> $LOGFILE 2>&1 &
 	;;
	stop)
		/sbin/start-stop-daemon --stop --pidfile $PIDFILE
		cd $FOLDER
		$DAEMON stop
	;;
	restart)
		$0 stop
		$0 start
	;;
	*)
		echo "Usage: $(basename $0) [start|stop|restart]" >&2
		exit 1
	;;
esac
